
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 17 00:53:42 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 36;
  public static final int CONST = 5;
  public static final int GREATEROREQUAL = 30;
  public static final int NOTEQUAL = 28;
  public static final int LPAREN = 10;
  public static final int GREATER = 29;
  public static final int SEMI = 6;
  public static final int MINUS = 19;
  public static final int RPAREN = 11;
  public static final int CHECKEQUAL = 27;
  public static final int BOOL = 35;
  public static final int COMMA = 8;
  public static final int INC = 25;
  public static final int DIV = 22;
  public static final int LESSER = 31;
  public static final int PLUS = 20;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 7;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 34;
  public static final int MOD = 23;
  public static final int IDENT = 33;
  public static final int VOID = 9;
  public static final int COLON = 14;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 12;
  public static final int READ = 16;
  public static final int LESSEROREQUAL = 32;
  public static final int GOTO = 18;
  public static final int RSQUARE = 13;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 26;
  public static final int PRINT = 17;
}

